name: Testing Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code/repository
        uses: actions/checkout@v4

      - name: Cek hasil Checkout
        run: |
          ls -a
          ls -l

      - name: Execute remote SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST}}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            echo "List Directory"
            ls -a

            echo "Change directory to target directory"
            cd /home/wawan/intro-pipepine-github

            echo "Pull Latest Code"
            git pull origin main

      - name: Deploy to server
        run: |
          echo "Hellow"
          echo "World"
