name: Testing Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code/repository
        uses: actions/checkout@v4

      - name: Execute remote SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST}}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: whoami

    #   - name: Deploy to server
    #     run: |
    #       echo "Deploying to server..."
    #       # ssh user@server "cd /path/to/app && git pull && npm install && pm2 restart app"
