name: Testing Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login ke VPS dan auto deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS1_HOS}}
          username: ${{ secrets.VPS1_USER }}
          key: ${{ secrets.VPS1_PASSWORD }}
          port: 22
          script: |
            echo "List Directory"
            ls -a

            echo "Change directory to target directory"
            cd /home/wawan/intro-pipepine-github

            echo "Pull Latest Code"
            git pull origin main
